name: Local

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
  
  install dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
      
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Run cargo-tarpaulin
      run: cargo tarpaulin --verbose --out Xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml

  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Run clippy
      run: cargo clippy --verbose --all-targets --all-features -- -D warnings
    - name: Run rustfmt
      run: cargo fmt --verbose --all -- --check

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Run cargo audit
      run: cargo audit
  documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Run cargo doc
      run: cargo doc --verbose --no-deps
    - name: Archive documentation
      uses: actions/upload-artifact@v1
      with:
        name: documentation
        path: target/doc
